Repository AY2122S2-CS2103-W17-3/tp, pull requests merged in 2022-04, with the labels that each got.

#153 Further validation of addCommand for email domain with added test for validity
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Email.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
Labels: bug, documentation

#154 Fix bug with file chooser, and modify behaviour of insurance package
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DeletePackageCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: bug

#161 Add more diagrams and explanation for DG for packageWindow UI and FindCommand
  docs/DeveloperGuide.md
  docs/diagrams/FieldContainsKeywordsPredicate.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/ParseFindSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/FieldContainsKeywordsPredicate.png
  docs/images/FindSequenceDiagram.png
  docs/images/ParseFindSequenceDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation

#177 Make small updates to documentation and code
  README.md
  docs/UserGuide.md
  docs/team/leeyiheng12.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddPackageCommand.java
  src/main/java/seedu/address/logic/commands/DeletePackageCommand.java
  src/main/java/seedu/address/logic/parser/AddPackageCommandParser.java
  src/main/java/seedu/address/logic/parser/EditPackageCommandParser.java
  src/test/java/seedu/address/logic/commands/DeletePackageCommandTest.java
  src/test/java/seedu/address/logic/parser/AddPackageCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditPackageCommandParserTest.java
Labels: documentation, priority.Low

#183 Add documentation
  docs/DeveloperGuide.md
  docs/team/leeyiheng12.md
  src/main/java/seedu/address/logic/commands/DeletePackageCommand.java
  src/main/java/seedu/address/logic/commands/EditPackageCommand.java
  src/main/java/seedu/address/logic/commands/ExportToCsvCommand.java
  src/main/java/seedu/address/logic/commands/ImportFromCsvCommand.java
Labels: documentation
