Repository AY2122S2-CS2103-W17-3/tp, pull requests merged in 2022-03, with the labels that each got.

#38 Refine 'find' command to include multi-field finding and multi-keywords finding
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/predicates/AddressContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/CombineContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/FieldContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/InsurancePackageContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/TagsContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/predicates/AddressContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/CombineContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/InsurancePackageContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/TagsContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/PredicatesListBuilder.java
Labels: enhancement, priority.Medium

#39 Minor bugfixes
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/storage/CommandStorage.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: bug

#42 Create a light theme for users
  src/main/resources/images/address_book_32.png
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: enhancement, type.Story, priority.Low

#44 Fix empty list cell colouring for light theme
  src/main/resources/view/DarkExtensions.css
  src/main/resources/view/LightExtensions.css
  src/main/resources/view/MainWindow.fxml
Labels: bug

#45 Add priority to tag
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/Priority.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/CsvAdaptedPerson.java
  src/main/java/seedu/address/storage/CsvAdaptedTag.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/predicates/TagsContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/CsvAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement, type.Story

#47 Add a check if previous command was undoable
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
Labels: bug, priority.Medium

#49 Fix bug in empty table colouring
  src/main/resources/view/LightTheme.css
Labels: bug, priority.Low

#48 Fix bug in undo command which caused undo to not work
  src/main/java/seedu/address/model/ModelManager.java
Labels: bug, priority.High

#53 Update user guide and developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FieldContainsKeywordsPredicate.puml
  docs/diagrams/FindCommand.puml
  docs/images/FieldContainsKeywordsPredicate.png
  docs/images/FindCommand.png
  docs/images/findUndecidedDavid.png
Labels: documentation

#56 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/SaveAddressBookToCsv.puml
  docs/images/SaveAddressBookToCsv.png
Labels: documentation

#67 Update User Guide
  docs/UserGuide.md
Labels: documentation

#72 Update UG to include some new commands
  docs/UserGuide.md
  docs/images/Ui.png
  docs/index.md
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/DeletePackageCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/EditTagCommand.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/address/logic/parser/EditTagCommandParser.java
Labels: documentation, priority.Low
